[package]
name = "ycrawl-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
url.workspace = true
futures-util.workspace = true
serde_yaml = "0.9"
encoding_rs = "0.8"

wreq = { version = "6.0.0-rc.29", features = ["stream"] }
wreq-util = "3.0.0-rc.6"
dom_smoothie = "0.18"
htmd = "0.5"
dom_query = "0.28"
pdf-extract = "0.12"
fantoccini = { version = "0.22", default-features = false, features = ["rustls-tls"] }
